language: c

sudo: false

addons:
    coverity_scan:
        project:
            name: capone-project/capone-core
        notification_email: coverity@pks.im
        build_command_prepend: ./scripts/deps.sh
        build_command: ./scripts/build.sh
        branch_pattern: coverity

cache:
    directories:
        - $HOME/local

env:
    global:
        - GENERATOR="Unix Makefiles"

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang
        - os: linux
          compiler: clang
          env: CFLAGS='-fsanitize=address -fsanitize=undefined'

install:
    - test ${TRAVIS_BRANCH} != coverity -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
    - ./scripts/deps.sh

script:
    - test ${TRAVIS_BRANCH} != coverity -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
    - ./scripts/build.sh
    - ./scripts/test.sh
