language: c

sudo: false

cache:
    directories:
        - $HOME/local

env:
    global:
        - GENERATOR="Unix Makefiles"

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang
        - os: linux
          compiler: clang
          env: CFLAGS='-fsanitize=address -fsanitize=undefined'
    allow_failures:
        - env: CFLAGS='-fsanitize=address -fsanitize=undefined'

install:
    - ./scripts/deps.sh

script:
    - ./scripts/build.sh
    - ./build/test/cpn-test --verbose
    - ./build/test/cpn-bench-throughput --encrypted 256 512
    - ./build/test/cpn-bench-throughput --plain 256 512
    - ./build/test/cpn-bench-latency 512
