language: c

sudo: false

cache:
    directories:
        - /tmp

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

install:
    - ./scripts/deps.sh

script:
    - ./scripts/build.sh
    - ./source/sd/build/sd-test --verbose
