cache:
    - C:\msys64\home\appveyor\local -> scripts\deps.sh

install:
    - C:\msys64\usr\bin\pacman.exe -Sy --noconfirm msys2-runtime msys2-runtime-devel
    - C:\msys64\usr\bin\sh.exe --login /c/projects/sd/scripts/deps.sh

build_script:
    - C:\msys64\usr\bin\sh.exe --login /c/projects/sd/scripts/build.sh

test_script:
    - C:\msys64\usr\bin\sh.exe --login -c 'PATH="${PATH}:${HOME}/local/bin" /c/projects/sd/source/sd/build/sd-test.exe --verbose'
