environment:
    matrix:
        - GENERATOR: "Unix Makefiles"
          TARGET: x86_64-pc-msys
          ARCH: 64

cache:
    - C:\msys64\home\appveyor\local -> scripts\deps.sh

install:
    - C:\msys64\usr\bin\pacman.exe -Sy --noconfirm cmake
    - C:\msys64\usr\bin\sh.exe --login /c/projects/capone-core/scripts/deps.sh

build_script:
    - C:\msys64\usr\bin\sh.exe --login /c/projects/capone-core/scripts/build.sh

test_script:
    - C:\msys64\usr\bin\sh.exe --login /c/projects/capone-core/scripts/test.sh
